### ISSUE TITLE
[Android Bootcamp] Tip Calculator - Review my app

### ISSUE THREAD

**Issue by dpkagrawal** [dpkagrawal/AndroidTipCalculator#1]
Please can you review it. And let me know for improvements in using number of views. /cc @nesquena @timothy1ee

-Deepak Agrawal

**Comment by nesquena** [comment]
Deepak: :+1: nice work. First off, a few quick notes after my review:
- Nice use of nested linear layouts for positioning (could also do it all with just a relative layout)
- Good to see one `calculateTip` method used for all three buttons
- Nice clear button functionality
- Might consider using Toast to display error to user (i.e if amount is invalid or blank)

One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I'm glad you have started that early and I would encourage you to push the projects each week, continue adding your own UI elements and experimenting with optional features that improve the user experience. 

We have provided a detailed [Project 1 Feedback Guide here](https://gist.github.com/nesquena/2e76670cfb4e751caf95) which covers the most common points we see for this project. Read through the [feedback guide point-by-point](https://gist.github.com/nesquena/2e76670cfb4e751caf95) to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this has given you a first sense of the RelativeLayout which is a very powerful layout system, probably one of the best responsive-first layout systems available across web and mobile platforms. The next assignment will build on top of the first concepts introduced here and will also introduce networking, api use, handling remote images and navigating between activities.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or post on the discussion forum on Canvas.
